name: test-deploy
on:
  schedule:
    - cron: '0 3 * * 6' # everyday at 10am

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          docker build -t gisops/valhalla:latest .
      - name: Test image
        run : /bin/bash -c "./tests/test.sh"
      - name: Upload image
  
