name: ci tests
on:
  push:
    paths-ignore:
      - '.gitignore'
      - '**.md'
    branches:
      - master
  pull_request:
    paths-ignore:
      - '.gitignore'
      - '**.md'
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          docker build -t gisops/valhalla:latest .
      - name: Test image
        run : |
          sudo apt-get update > /dev/null
          sudo apt-get install -y moreutils tree > /dev/null
          /bin/bash -c "./tests/test.sh"
